using System.Text.Json.Serialization;
using Kodosi.Host.Realtime;

namespace Kodosi.Host.Serialization;

[JsonSerializable(typeof(WsEnvelope))]
[JsonSerializable(typeof(DeviceProofChallengeMessage))]
[JsonSerializable(typeof(DeviceProofResponseMessage))]
[JsonSerializable(typeof(HostHelloMessage))]
[JsonSerializable(typeof(HostEndMessage))]
[JsonSerializable(typeof(HostAcceptedMessage))]
[JsonSerializable(typeof(HostFenceAckMessage))]
[JsonSerializable(typeof(HostStreamDemandMessage))]
[JsonSerializable(typeof(HostKeyDistributionRequestedMessage))]
[JsonSerializable(typeof(HostActionResultMessage))]
[JsonSerializable(typeof(HostActionResultAckMessage))]
[JsonSerializable(typeof(HostSemanticSendMessage))]
[JsonSerializable(typeof(HostSemanticCancelMessage))]
[JsonSerializable(typeof(HostSemanticReceiptMessage))]
[JsonSerializable(typeof(HostSemanticReceiptAckMessage))]
[JsonSerializable(typeof(HostStopMessage))]
[JsonSerializable(typeof(HostInterruptMessage))]
[JsonSerializable(typeof(HostInputMessage))]
[JsonSerializable(typeof(HostResizeMessage))]
[JsonSerializable(typeof(HostFocusChangedMessage))]
[JsonSerializable(typeof(HostParticipantDisconnectedMessage))]
[JsonSerializable(typeof(HostSuggestionMessage))]
[JsonSerializable(typeof(HostPermissionDecisionMessage))]
[JsonSerializable(typeof(ParticipantSemanticSendMessage))]
[JsonSerializable(typeof(ParticipantSemanticCancelMessage))]
[JsonSerializable(typeof(ParticipantSemanticReceiptMessage))]
[JsonSerializable(typeof(ParticipantSemanticReceiptAckMessage))]
[JsonSerializable(typeof(ParticipantJoinMessage))]
[JsonSerializable(typeof(ParticipantSuggestMessage))]
[JsonSerializable(typeof(ParticipantInjectMessage))]
[JsonSerializable(typeof(ParticipantResizeMessage))]
[JsonSerializable(typeof(ParticipantFocusChangedMessage))]
[JsonSerializable(typeof(ParticipantPermissionDecisionMessage))]
[JsonSerializable(typeof(ParticipantStopMessage))]
[JsonSerializable(typeof(ParticipantInterruptMessage))]
[JsonSerializable(typeof(ParticipantAcceptedMessage))]
[JsonSerializable(typeof(ActionResultMessage))]
[JsonSerializable(typeof(SessionStatusMessage))]
[JsonSerializable(typeof(SessionEndedMessage))]
[JsonSerializable(typeof(HostParticipantChangedMessage))]
[JsonSerializable(typeof(HostAccessRevokedMessage))]
[JsonSerializable(typeof(SessionAccessRevokedMessage))]
[JsonSerializable(typeof(KeyRotationMessage))]
[JsonSerializable(typeof(DiscoveryInvalidatedMessage))]
[JsonSerializable(typeof(UserDeviceListChangedMessage))]
[JsonSerializable(typeof(UserIdentityLifecycleChangedMessage))]
[JsonSerializable(typeof(UserDeviceLinkSnapshotMessage))]
[JsonSerializable(typeof(UserDeviceLinkRequestedMessage))]
[JsonSerializable(typeof(UserDeviceLinkResolvedMessage))]
public sealed partial class WsJsonContext : JsonSerializerContext;
