language = "C"
pragma_once = true
cpp_compat = true
include_guard = "KODOSI_RUNTIME_H"
documentation = false

[export]
prefix = ""
include = []

[export.rename]
"KodosiCallbacks" = "kodosi_callbacks_t"
"KodosiStartFailure" = "kodosi_start_failure_t"
"EventCb" = "kodosi_event_cb_t"
"TerminalDataCb" = "kodosi_terminal_data_cb_t"
"TerminalControlCb" = "kodosi_terminal_control_cb_t"
"TerminalConnectResultCb" = "kodosi_terminal_connect_result_cb_t"
"TerminalCheckpointCb" = "kodosi_terminal_checkpoint_cb_t"

[parse]
parse_deps = false
include = []

[fn]
prefix = ""
postfix = ""
sort_by = "None"
