[package]
edition = "2024"
name = "kodosi-domain"
publish = false
rust-version = "1.97.1"
version = "0.1.0"

[dependencies]
base64 = { workspace = true }
serde = {workspace = true, features = ["derive"]}
specta = {workspace = true, features = ["derive", "serde_json"]}
thiserror = {workspace = true}
time = {workspace = true, features = ["formatting", "parsing", "serde"]}
uuid = {workspace = true}

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
