[package]
edition = "2024"
name = "kodosi-backend-client"
publish = false
rust-version = "1.97.1"
version = "0.1.0"

[dependencies]
aes-gcm = "0.11.0"
aws-lc-rs = {workspace = true}
base64 = {workspace = true}
bytes = {workspace = true}
futures-util = {workspace = true}
getrandom = {workspace = true}
hkdf = "0.13.0"
kodosi-domain = {path = "../kodosi-domain"}
rand = "0.10.2"
reqwest = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
sha2 = "0.11.0"
thiserror = {workspace = true}
time = {workspace = true, features = ["serde-well-known"]}
tokio = {workspace = true, features = ["macros", "net", "rt", "sync", "time"]}
tokio-tungstenite = {workspace = true}
tokio-util = {workspace = true, features = ["rt"]}
tracing = {workspace = true}
uuid = {workspace = true}
zeroize = {workspace = true}

[lints]
workspace = true
